[build-system]
requires = ["setuptools>=42"]
build-backend = "setuptools.build_meta"

[project]
name = "diff_ddpc"
version = "0.1"
dependencies = [
  "cvxpy",
  "cvxpylayers",
  "array-api-compat",
  "numpy",
  "torch",
]
